version: '3.3'

services:
  web-service:
    depends_on:
      - model-service
    image: pleuzhaw/consumeajrizple:latest
    ports:
      - "80:8082"
    restart: always
    networks:
      - apps-network

  model-service:
    image: pleuzhaw/djl-serving:latest
    restart: always
    networks:
      - apps-network 

networks:
  apps-network:
    driver: bridge

